import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react";

import {Header1} from '../components/Header.js'
import SliderBackground from '../components/SliderBackground.js'
import HomeCard from '../components/HomeCard.js'
import {homeObjOne, homeObjTwo, homeObjThree} from '../data/HomeCardData.js';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
      <Header1/>
      <SliderBackground/>
      <HomeCard {...homeObjOne}/>
      <HomeCard {...homeObjTwo}/>
      <HomeCard {...homeObjThree}/>
      </div>

    </div>
  )
}
